DROP TABLE IF EXISTS ingest_tasks;
DROP TABLE IF EXISTS paper_chunks;
DROP TABLE IF EXISTS papers;
DROP TABLE IF EXISTS eval_runs;

CREATE TABLE papers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  title VARCHAR(512) NOT NULL,
  abstract_text CLOB,
  authors VARCHAR(512),
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  doi VARCHAR(128),
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_tenant_status_time ON papers (tenant_id, status, created_at);
CREATE UNIQUE INDEX uk_tenant_doi ON papers (tenant_id, doi);

CREATE TABLE ingest_tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  paper_id BIGINT NOT NULL,
  tenant_id BIGINT NOT NULL,
  biz_key VARCHAR(128) NOT NULL,
  status VARCHAR(32) NOT NULL,
  error_message VARCHAR(1024),
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  CONSTRAINT fk_ingest_tasks_paper FOREIGN KEY (paper_id) REFERENCES papers(id)
);

CREATE UNIQUE INDEX uk_ingest_task_tenant_biz_key ON ingest_tasks (tenant_id, biz_key);
CREATE UNIQUE INDEX uk_ingest_task_paper_biz_key ON ingest_tasks (paper_id, biz_key);

CREATE TABLE paper_chunks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  paper_id BIGINT NOT NULL,
  tenant_id BIGINT NOT NULL,
  chunk_index INT NOT NULL,
  content CLOB NOT NULL,
  token_count INT NOT NULL,
  created_at TIMESTAMP NOT NULL,
  CONSTRAINT fk_paper_chunks_paper FOREIGN KEY (paper_id) REFERENCES papers(id)
);

CREATE UNIQUE INDEX uk_paper_chunk_index ON paper_chunks (paper_id, chunk_index);
CREATE INDEX idx_paper_chunks_tenant_paper ON paper_chunks (tenant_id, paper_id);

CREATE TABLE eval_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  ground_truth_chunk_ids CLOB NOT NULL,
  retrieved_chunk_ids CLOB NOT NULL,
  k INT NOT NULL,
  recall_at_k DOUBLE NOT NULL,
  mrr DOUBLE NOT NULL,
  ndcg_at_k DOUBLE NOT NULL,
  created_at TIMESTAMP NOT NULL
);
